title: Ursus Core Jekyll Theme
author: Ryan Underwood
email: ryan@takenot.es
description: Ursus is a jekyll theme that is barebones from the start. It's meant to be heavily modified as needed, but structured in a way that can be built on.
favicon: /assets/imgs/favicon.png
logo: /assets/imgs/logo.svg
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
copy_year: 2023
social:
  - title: Twitter
    user: takenot.es
    url:
  - title: Dribbble
    user: takenot.es
    url:
  - title: Facebook
    user: Ryan Underwood
    url: 
  - title: GitHub
    user: takenot.es
    url:

# Placement of JS Links. Can go in header or footer or both. Boolean options true or false
scripts_in_header: false
scripts_in_footer: true

google_tag: G-XXXXXXXXXX

sass:
  sass_dir: /assets/sass/
  style: compressed

collections: 
  pages:
    output: true
    permalink: /:title/

enable_compress_html: false
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: true
  startings: [html, head, body]


plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
